import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnBig } from "lucide-react";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}  antialiased`}>
        <nav className="bg-primary p-4 text-white h-10 flex justify-between items-center">
          <Link className="font-bold text-2xl gap-1 flex items-center" href="/">
            <ChartColumnBig className="text-lime-500" />
            NextCash
          </Link>
          <div>auth</div>
        </nav>
        {children}
      </body>
    </html>
  );
}
